name: Release

on:
  push:
    branches:
      - main

# Add permissions to create releases
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run semantic-release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          changelog-file: CHANGELOG.md
          update-file: VERSION

      - name: Build binaries
        if: steps.semrel.outputs.version != ''
        run: |
          mkdir -p dist
          VERSION="${{ steps.semrel.outputs.version }}"
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-windows-amd64.exe
      
      - name: Attach binaries to release
        if: steps.semrel.outputs.version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.semrel.outputs.version }}
          files: |
            dist/* 