name: Release

on:
  push:
    branches:
      - main

# Add permissions to create releases
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release

      - name: Build binaries
        if: ${{ env.RELEASED == 'true' }}
        run: |
          mkdir -p dist
          VERSION="${SEMANTIC_VERSION#v}"
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o dist/rf-migrate-windows-amd64.exe
      
      - name: Attach binaries to release
        if: ${{ env.RELEASED == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.SEMANTIC_VERSION }}
          files: |
            dist/* 