name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Build for all platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/v}" -o dist/rf-migrate-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/v}" -o dist/rf-migrate-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/v}" -o dist/rf-migrate-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/v}" -o dist/rf-migrate-windows-amd64.exe
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          generate_release_notes: true 